---
title: "test-problems"
output: html_document
---

```{r knit2synapse, eval=FALSE}
library(synapser)
library(knit2synapse)

synLogin()

knit2synapse::createAndKnitToFolderEntity(file = "debug.Rmd",
                                 parentId ="syn21725610",
                                 folderName = "debugME")
```

```{r libs, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
## Load required libraries
library(CovariateAnalysis) # get the package from devtools::install_github('th1vairam/CovariateAnalysis@dev')
library(data.table)
library(tidyr)
library(tibble)
library(plyr)
library(dplyr)
library(stringr)
library(R.utils)
library(ggplot2)
library(limma)
library(psych)
library(edgeR)
library(cqn)
library(lme4)
library(biomaRt)
#devtools::install_github("GabrielHoffman/variancePartition@613dfe9")
library(variancePartition)
library(synapser)
library(knitr)
library(githubr) # get the package from devtools::install_github('brian-bot/githubr')
library(BiocParallel)
param = SnowParam(4, "SOCK", progressbar=TRUE)

synLogin()

# library(doParallel)
library(foreach)

# cl = makeCluster(detectCores(TRUE)-2)
# 
# registerDoParallel(cl)

options(xtable.type="html")

knitr::opts_chunk$set(
  echo=FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  cache = TRUE)
```


```{r library}
# NEW.COUNTS <- 
  
NEW.COUNTS <- read.table(synGet("syn21725766")$path, sep = "\t", header = TRUE)
rownames(NEW.COUNTS) <- NEW.COUNTS$genes
NEW.COUNTS$genes <- NULL
COVARIATES <- read.table(synGet("syn21725830")$path, sep = "\t", header = TRUE)
rownames(COVARIATES) <- COVARIATES$sampleid
COVARIATES$sampleid <- NULL
CQN.GENE_EXPRESSION$E <- read.table(synGet("syn21725967")$path, sep = "\t", header = TRUE)
rownames(CQN.GENE_EXPRESSION$E) <- CQN.GENE_EXPRESSION$E$genes
CQN.GENE_EXPRESSION$E$genes <- NULL
```

```{r iterative.normalisation}
adjust.covars <- c("Dx.Tissue", "RIN", "IntronicRate")

writeLines(paste('Using following covariates in the model:',
                 paste(adjust.covars, collapse=', '),
                 'as fixed effects and Individual_ID is chosen as random effect'))

# Post adjusted formula
random_effect <- "Individual_ID"
formula <- glue::glue("~ ", glue::glue_collapse(adjust.covars, sep = " + ")) %>% 
  glue::glue(" + (1|{random_effect})")

# Estimate voom weights with DREAM
geneExpr = DGEList(NEW.COUNTS)
geneExpr = edgeR::calcNormFactors(geneExpr)
message("pass")
VOOM.GENE_EXPRESSION = variancePartition::voomWithDreamWeights(counts = geneExpr, 
                                                               formula = formula,
                                                               data = COVARIATES,
                                                               save.plot = TRUE)
message("pass")
# How to plot a voom object if save.plot=TRUE
# Set plot generic to voom result EList
#' @export
setMethod("plot", signature(x="EList", y="missing"),
  function(x,  y, ...){
    if( is.null(x$voom.xy) || is.null(x$voom.line)){
        stop("x does not contain the trend information.\nvoom() must be run with save.plot=TRUE")
    }
    # points
    df = data.frame(x = x$voom.xy$x,
                    y = x$voom.xy$y)
    # trend line
    df.line = data.frame(x = x$voom.line$x,
                        y = x$voom.line$y)
    ggplot(df, aes(x,y)) + geom_point(size=.1) + theme_bw(15) + 
      theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5)) + 
      geom_line(data=df.line, aes(x,y), color="red") + xlab(bquote(log[2](count + 0.5))) + 
      ylab(expression( sqrt("standard deviation"))) + ggtitle("Voom: Mean-variance trend") + 
      ylim(0, max(df$y))
  }
)
message("pass")  
plot(VOOM.GENE_EXPRESSION)

# Fit linear model using new weights and new design
VOOM.GENE_EXPRESSION$E = CQN.GENE_EXPRESSION$E
Dx.Tissue_ADJUSTED.FIT = variancePartition::dream(exprObj = VOOM.GENE_EXPRESSION,
                                        formula = formula,
                                        data = COVARIATES,
                                        computeResiduals = TRUE)
message("pass")
col_type <- dplyr::select(COVARIATES, c(adjust.covars, "Individual_ID")) %>%
  dplyr::summarise_all(class) %>% 
  tidyr::gather(variable, class)

# Model categorical variables as random to report variance fractions
formula_for_variance_fractions = sapply(1:length(col_type$class), function(i){
  switch(col_type$class[i], 
    "factor" = paste0('(1|', col_type$variable[i], ')'),
    "numeric" = col_type$variable[i])
  })

formula_for_variance_fractions <- glue::glue("~ ", glue::glue_collapse(formula_for_variance_fractions, sep = " + "))

violin_plot <- variancePartition::fitExtractVarPartModel(VOOM.GENE_EXPRESSION,
                                                         formula = formula_for_variance_fractions,
                                                         data = COVARIATES)
message("pass")
plotVarPart(sortCols(violin_plot))

# Residuals after normalisation
Dx.Tissue_RESIDUAL.GENE_EXPRESSION = residuals(Dx.Tissue_ADJUSTED.FIT, CQN.GENE_EXPRESSION$E)

# Find PC of residual gene expression and significant covariates that are highly correlated with PCs
residualSigCovars = runPCAandPlotCorrelations(Dx.Tissue_RESIDUAL.GENE_EXPRESSION, COVARIATES,
                                              'adjusted design(voom-normalized)',
                                              isKeyPlot=TRUE)
```

```{r store}
CODE <- Folder(name = "debugME", parentId = "syn21725610")
CODE <- synStore(CODE)
```

