default:
  counts:
    synID:
  metadata:
    synID:
rosmap:
  counts:
    synID: syn21075911
  clinical metadata:
    synID: syn3191087
    version: 9
  protected clinical metadata:
    synID: syn7116000
  assay metadata:
    synID: syn4300313
  sequencing metadata:
    synID: syn21075912
  mapping:
    synID: syn3382527
    version: 7
  synID mapping:
    synID: syn21075913
mssm:
  counts:
    synID: syn21544664
  clinical metadata:
    synID: syn6101474
    version: 4
  protected clinical metadata:
    synID: syn10156693
    version: 4
  assay metadata:
    synID: syn6100548
    version: 10
  sequencing metadata:
    synID: syn21544666
  Synapse folder:
    synID: syn21562888
mayo:
